### ISSUE TITLE
Parameterization of displacement fields

### ISSUE THREAD

**Issue by WangJYao** [uncbiag/NAISR#1]
Hello, I have read your paper and would like to ask you a question：
How to understand
 'To assure that a zero covariate value results in a zero displacement we parameterize the displacement fields as di = gi(p, ci, 0, z)'
'gi(p, x, y, z) = fi(p, x, z) − fi(p, y, z) .'
And how it is implemented in the code.

I look forward to your reply.

**Comment by jiaoyining** [comment]
Thanks for asking。
In the code this is the function for getting the displacement:
```python
def get_displacement_per_covariate(self, enc_coords, embedding, covaraite, which_covariate, whether_inv=False, training=True):

        embedding_with_attri = torch.cat((covaraite, embedding), dim=-1)
        if training:
            embedding_with_zeros = torch.cat((torch.randn_like(covaraite)*1e-3, embedding), dim=-1)
        else:
            embedding_with_zeros = torch.cat((torch.zeros_like(covaraite) * 1e-3, embedding), dim=-1)

        arr_disp = self.net_direction[which_covariate](embedding_with_attri, enc_coords) - self.net_direction[which_covariate](embedding_with_zeros, enc_coords)
        if not whether_inv:
            return arr_disp
        else:
            return -arr_disp
```

```self.net_direction()``` is the f(p, x, z), x is a single covariate for example age.
and ```arr_disp``` give the covariate-wise displacement, which is ```gi(p, x, y, z) = fi(p, x, z) − fi(p, y, z)```. In this case, y is set to 0 so you get gi=0 when x=0.
During training, we add an extremely small value to 0 as ``` embedding_with_zeros = torch.cat((torch.randn_like(covaraite)*1e-3, embedding), dim=-1)``` as data augmentation for robustness.

**Comment by jiaoyining** [comment]
> 

Yes exactly. And the model is there ```naisr/model_naigsr.py```
