### ISSUE TITLE
The inverse consistency loss

### ISSUE THREAD

**Issue by WangJYao** [uncbiag/NAISR#2]
I don't understand the ' inv_loss' in the code

    current = l1_loss(pred_vec_fields[name][torch.abs(gt_sdf[:,:,0])<0.01, :], -pred_vec_fields[name[0:-4]][torch.abs(gt_sdf[:,:,0])<0.01, :])

What does ' torch.abs(gt_sdf[:,:,0])<0.01 ' mean?

**Comment by jiaoyining** [comment]
HI,

It means points on the surface are selected for this L1 loss.
Sorry for the late reply.
